-- AlterTable
ALTER TABLE "AgendaItem" ALTER COLUMN "durationMinutes" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "maxMinutes" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "minMinutes" SET DATA TYPE DOUBLE PRECISION;
